# Generated by Django 4.1 on 2022-10-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_apt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upcomming_apt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('apt_time', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dentist')),
            ],
        ),
    ]
