# Generated by Django 4.1 on 2022-10-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('web', models.URLField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='upcomming_apt',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomming_apt',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dentist'),
        ),
        migrations.AddField(
            model_name='upcomming_apt',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.venue'),
        ),
    ]
