# Generated by Django 4.1 on 2022-10-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_nurse_delete_customer_dentist_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='emial',
            new_name='email',
        ),
    ]
