# Generated by Django 4.1 on 2022-10-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_finished_apt_assistance_tracker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomming_apt',
            name='assistance_tracker',
        ),
    ]
