# Generated by Django 4.1 on 2022-10-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_upcomming_apt_assistance_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_apt',
            name='assistance_tracker',
        ),
    ]
