# Generated by Django 4.1 on 2022-12-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_finished_apt_assistance_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('querytime', models.DateTimeField(blank=True, null=True, verbose_name='Query Time')),
                ('querysite', models.URLField(verbose_name='Website to Query')),
            ],
        ),
    ]
