# Generated by Django 4.1 on 2022-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_cppdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Htmldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_link', models.CharField(max_length=200, verbose_name='First Name')),
                ('data_name', models.CharField(max_length=200, verbose_name='First Name')),
            ],
        ),
    ]
