# Generated by Django 4.1 on 2022-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_htmldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmldata',
            name='data_link',
            field=models.CharField(max_length=200, verbose_name='Data Link'),
        ),
        migrations.AlterField(
            model_name='htmldata',
            name='data_name',
            field=models.CharField(max_length=200, verbose_name='Data Name'),
        ),
    ]
