# Generated by Django 4.1 on 2022-12-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_venue_manager_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
