# Generated by Django 4.1 on 2022-12-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomming_apt',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
