# Generated by Django 4.1 on 2022-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_upcomming_apt_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('RN', 'NURSE'), ('TEC', 'TECHNICIAN'), ('DEN', 'DENTIST')], max_length=3, verbose_name='Position')),
                ('fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=25, verbose_name='Email')),
                ('education', models.CharField(choices=[('BA', 'Bachelors'), ('MA', 'Masters'), ('DR', 'PhD')], max_length=3, verbose_name='Education')),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
