# Generated by Django 4.1 on 2022-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_jobdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='education',
            field=models.CharField(choices=[('BA', 'Bachelors'), ('MA', 'Masters'), ('DR', 'PhD')], max_length=20, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='position',
            field=models.CharField(choices=[('RN', 'NURSE'), ('TEC', 'TECHNICIAN'), ('DEN', 'DENTIST')], max_length=20, verbose_name='Position'),
        ),
    ]
