# Generated by Django 4.1 on 2022-12-26 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='year',
            field=models.PositiveSmallIntegerField(default=2008, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
