# Generated by Django 4.1 on 2022-12-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_interview_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('book_author', models.CharField(max_length=200, verbose_name='Book Author')),
            ],
        ),
    ]
