# Generated by Django 4.1 on 2022-12-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
